function Cd = Cdhw7(alpha,beta,gamma)
%CDHW7
%    CD = CDHW7(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jul-2019 21:30:25

t2 = sin(alpha);
Cd = reshape([0.0,-1.0./(t2.*2.0+3.0).^2.*(t2.*6.0+4.0),cos(beta).*(2.0./5.0),1.0./sin(beta).^2,cos(gamma).*(3.0./5.0),0.0],[2,3]);
