function C = Chw7(alpha,beta,gamma)
%CHW7
%    C = CHW7(ALPHA,BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jul-2019 21:30:24

t2 = sin(beta);
C = [t2.*(2.0./5.0)+sin(gamma).*(3.0./5.0)-9.0./1.0e1;cos(alpha)./(sin(alpha)+3.0./2.0)-cos(beta)./t2];
