function x6dd = x6ddhw7(betad,betadd,beta,gammad,gammadd,gamma)
%X6DDHW7
%    X6DD = X6DDHW7(BETAD,BETADD,BETA,GAMMAD,GAMMADD,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jul-2019 21:30:25

x6dd = betadd.*sin(beta).*(-7.0./1.0e1)-gammadd.*sin(gamma).*(3.0./5.0)-betad.^2.*cos(beta).*(7.0./1.0e1)-gammad.^2.*cos(gamma).*(3.0./5.0);
