function x6d = x6dhw7(betad,beta,gammad,gamma)
%X6DHW7
%    X6D = X6DHW7(BETAD,BETA,GAMMAD,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jul-2019 21:30:25

x6d = betad.*sin(beta).*(-7.0./1.0e1)-gammad.*sin(gamma).*(3.0./5.0);
