function x6 = x6hw7(beta,gamma)
%X6HW7
%    X6 = X6HW7(BETA,GAMMA)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Jul-2019 21:30:25

x6 = cos(beta).*(7.0./1.0e1)+cos(gamma).*(3.0./5.0);
